jenkins:
  systemMessage: "CORE ENG - Jenkins managed by JCasC for local testing!"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 5
  
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          password: "admin123"
        - id: "developer"
          password: "dev123"
  
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "USER:Overall/Read:authenticated"
        - "USER:Job/Build:authenticated"
        - "USER:Job/Cancel:authenticated"
        - "USER:Job/Read:authenticated"
        - "USER:Job/Workspace:authenticated"
        - "USER:View/Read:authenticated"

  remotingSecurity:
    enabled: true

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@localhost"
  
  globalLibraries:
    libraries:
      - name: "shared-library"
        defaultVersion: "main"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/your-org/jenkins-shared-library.git"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"
              username: "your-github-user"
              password: "your-github-token"
              description: "GitHub credentials for repository access"
          - string:
              scope: GLOBAL
              id: "api-token"
              secret: "your-secret-api-token"
              description: "API token for external services"


appearance:
  themeManager:
    disableUserThemes: true
    theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings

jobs:
  - script: |
      folder('pipelines') {
        displayName('Pipeline Jobs')
        description('Folder containing all pipeline jobs')
      }

  # Load all job definitions from jobs-config directory
  - file: /var/jenkins_home/casc_configs/jobs-config/test.groovy

  # You can add more job files here as needed
  # - file: /var/jenkins_home/casc_configs/jobs-config/production.groovy
  # - file: /var/jenkins_home/casc_configs/jobs-config/staging.groovy